name: Node.js CI
#language: node_js

node_js:
- node

env:
- MY_VAR=EverythignIsAwesome
- NODE_ENV=TEST

#cache: npm
on:
  push:
    branches: [ feature ]
  pull_request:
    branches: [ feature ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        #node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm build
    - run: npm test
    - echo 'feature branch triggered build successfully.'
