language: node_js
node_js:
  - 11.6.0

cache: npm

#build lifecycle

install:
  - npm ci

script:
  - npm test
  - npm run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: feature



# skip below life cycle as of now
#before_install:
#insatll:
#  - npm ci
#  - npm i -g webpack
#before_script:
#script:
#after_success:
#after_failure:
#after_script:

#before_deploy:
#depoy:
#after_deploy:
